
itemAttributes = {
    "itemType": ["Weapon", "Armor", "Potion", "Scroll", "Ring", "Necklace", "Wand", "Component", "Gold"],
    "weapon": ["sword", "axe", "bow", "spear", "dagger", "mace", "staff", "club", "crossbow", "flail", "hammer", "halberd", "lance", "morningstar", "pickaxe", "scythe", "shield", "sling", "trident", "whip", "boomerang", "chakram", "fist"],
    "armor": ["helmet", "chestplate", "leggings", "boots", "gloves", "cloak", "bracers", "belt"],
    "potion": ["health", "mana", "strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma", "speed", "stealth", "invisibility", "poison", "antidote", "fire", "ice", "lightning", "acid", "earth", "water", "air", "life", "death", "healing", "harming", "protection", "disruption", "teleportation"],
    "scroll": ["fireball", "heal", "lightning", "ice", "earthquake", "tornado", "haste", "slow", "confusion", "charm", "fear", "sleep", "paralysis", "blindness", "deafness", "silence", "invisibility", "poison", "antidote", "protection", "disruption", "teleportation"],
    "ring": ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma", "speed", "stealth", "invisibility", "protection", "disruption", "teleportation"],
    "wand": ["fire", "ice", "lightning", "acid", "earth", "water", "air", "life", "death", "healing", "harming", "protection", "disruption", "teleportation"],
    "component": ["wood", "iron", "steel", "mithril", "adamantine", "obsidian", "crystal", "bone", "leather", "cloth", "silk", "gold", "silver", "copper", "bronze", "brass", "platinum"]
}

# Item types will be here. Things like weapons, armor, potion, scrolls, etc.
# itemType = [
#     "Weapon",
#     "Armor",
#     "Potion",
#     "Scroll",
#     "Ring",
#     "Necklace",
#     "Wand",
#     "Component",
#     "Gold"
# ];
#
# # Weapon types will be here. Things like sword, axe, bow, etc.
# weapon = [
#     "sword",
#     "axe",
#     "bow",
#     "spear",
#     "dagger",
#     "mace",
#     "staff",
#     "club",
#     "crossbow",
#     "flail",
#     "hammer",
#     "halberd",
#     "lance",
#     "morningstar",
#     "pickaxe",
#     "scythe",
#     "shield",
#     "sling",
#     "trident",
#     "whip",
#     "boomerang",
#     "chakram",
#     "fist",
# ]
#
# # Armor types will be here. Things like helmet, chestplate, leggings, etc.
# armor = [
#     "helmet",
#     "chestplate",
#     "leggings",
#     "boots",
#     "gloves",
#     "cloak",
#     "bracers",
#     "belt",
# ]
#
# # Potion types will be here. Things like health, mana, strength, etc.
# potion = [
#     "health",
#     "mana",
#     "strength",
#     "dexterity",
#     "constitution",
#     "intelligence",
#     "wisdom",
#     "charisma",
#     "speed",
#     "stealth",
#     "invisibility",
#     "poison",
#     "antidote",
#     "fire",
#     "ice",
#     "lightning",
#     "acid",
#     "earth",
#     "water",
#     "air",
#     "life",
#     "death",
#     "healing",
#     "harming",
#     "protection",
#     "disruption",
#     "teleportation",
# ]
#
# # Scroll types will be here. Things like fireball, heal, etc.
# scroll = [
#     "fireball",
#     "heal",
#     "lightning",
#     "ice",
#     "earthquake",
#     "tornado",
#     "haste",
#     "slow",
#     "confusion",
#     "charm",
#     "fear",
#     "sleep",
#     "paralysis",
#     "blindness",
#     "deafness",
#     "silence",
#     "invisibility",
#     "poison",
#     "antidote",
#     "protection",
#     "disruption",
#     "teleportation",
# ]
#
# # Ring types will be here. Things like strength, dexterity, etc.
# ring = [
#     "strength",
#     "dexterity",
#     "constitution",
#     "intelligence",
#     "wisdom",
#     "charisma",
#     "speed",
#     "stealth",
#     "invisibility",
#     "protection",
#     "disruption",
#     "teleportation",
# ]
#
# # Wand types will be here. Things like fire, ice, etc.
# wand = [
#     "fire",
#     "ice",
#     "lightning",
#     "acid",
#     "earth",
#     "water",
#     "air",
#     "life",
#     "death",
#     "healing",
#     "harming",
#     "protection",
#     "disruption",
#     "teleportation",
# ]
#
# # Component types will be here. Things like wood, iron, etc.
# component = [
#     "wood",
#     "iron",
#     "steel",
#     "mithril",
#     "adamantine",
#     "obsidian",
#     "crystal",
#     "bone",
#     "leather",
#     "cloth",
#     "silk",
#     "gold",
#     "silver",
#     "copper",
#     "bronze",
#     "brass",
#     "platinum",
#     "diamond",
#     "emerald",
#     "ruby",
#     "sapphire",
#     "topaz",
#     "amethyst",
#     "pearl",
#     "jade",
#     "quartz",
#     "agate",
#     "malachite",
#     "lapis lazuli",
#     "turquoise",
#     "amber",
#     "jet",
#     "ivory",
#     "coral",
#     "dragonbone",
#     "dragonscale",
#     "dragonblood",
#     "phoenixfeather",
#     "unicornhorn",
#     "wyvernwing",
#     "gryphonclaw",
#     "krakenbeak",
#     "hydratooth",
#     "basiliskeye",
#     "minotaurhorn",
#     "harpyfeather",
#     "centaurhoof",
#     "pegasuswing",
#     "sphinxclaw",
#     "chimerafang",
#     "goblinear",
#     "orcishide",
#     "trollblood",
#     "ogrebone",
#     "giantfingernail",
#     "demonheart",
#     "angelwing",
#     "dwarvenbeard",
#     "elvenhair",
#     "gnomishat",
#     "hal"
# ]
#


